FROM golang:1.19-alpine as dlv
RUN go install github.com/go-delve/delve/cmd/dlv@latest

FROM alpine
WORKDIR /app
COPY ./build/ /app/build
COPY --from=dlv /go/bin/dlv /go/bin/dlv
CMD '/go/bin/dlv --listen=:2345 --continue --headless=true --api-version=2 --accept-multiclient exec /app/build/github-csat'