apiVersion: v1
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:T58wPLMfpPdR+c7boefsZqlUKAyA67EV1UQAtv/5mmJUYxaRAN66J0Zvy+GRKbo5GInfTa9wNjI8rF8YS/eo+AZB+kKy1d8LKWU63EBUGGUTpmzXGKnuj7WlwO9vIZGA19Q2qjy/+uXQ+JOVZGGTOfncWLF8GbANrdrqT2EeZBGxMuFEEl3pQfTNvrzbSaYSKIB7+xHAi05gUT65KxXt1oR1ErDKXuAms4nNqEtIPJluEg==,iv:70eVfSkWzffSTyJIDW1QHbIOdz8sQA+MhvRDfToSyYU=,tag:ljQSn1TBWC3U0owrSu35CQ==,type:str]
kind: Secret
metadata:
    name: ghcr-creds
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-28T00:23:22Z"
    mac: ENC[AES256_GCM,data:CWAKmqqTphmnK7hYucCoUQSbNOxZq0lc7Zvv+3tJDfLqPiuTY8JUc26oBLu+c+pyR5foM0DAsr6aN/A+UShqDpwLBPc/0N/Y+J2KkfUOaOuUKjZ4mIWYrUFCWM8UAiZEnW1wsx8rN3+uQHU7KXgSMMS8HymLBhKJRqmNk9sn91s=,iv:OXTqD6Mm70Y2Qx/pkgvHuvWIK2qFyg0Q/XCJ+ydAKl8=,tag:LCIz+UBPOcGnL5w220KYPg==,type:str]
    pgp:
        - created_at: "2022-12-28T00:23:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ/+MvPqofnbv1IJjbnUHJZSPKVLXApTKybJjLpsHYhpAPnh
            piS06kpHS4FEj3+RkhpkAJUdZ/LrTV9Gliy0NapBznLSNPK9pD5tmvjjCTncvoyX
            24EvoAFYMs8WvnA9RPYdAI7Dn5yoSVBjLpFSc+99NUVoPvRMZyZCm0F2FueOQhzm
            Sx4BI4aydm1uYwC+jCemrHLYmb0l7h8ZJfu8N4Z4nK95x4okK7u5w9MsxetCe0Dm
            l2xvh7qocSI4AXTY4CJ8is2BYObubpHd22Hci8Lw9iFZrIYNUQ87euJdnjiRtdOz
            ypCo7Utp0OK83uLYP6N8enV4+0yZUgMCc1Lyss8dLd3/wnE3oMDkuh18tYmE162P
            F3W2T8IdOPGGavqviv2LvpKCPw58qZX/5j51179HJPlgnCimuYBaUZ1Yop+wHsi8
            U6/+D6G0KGgWMb7+F+TxiQqkHXXh1h9z1asVjlUmOeg+FEnvE5BQ8mkKFCK1uc1e
            Ja6A+mwbncznT7s0ZVf32gzKIQXpPkoWigc7M12kS++sgiP+yPkyxdM4v85uPLR2
            mtsNA24cQ0Izhht5ROtvrxRBaI7sPVe9rgd+mow5IzCbOIR+HBe98P1wiTQ8QPdY
            5ADay63SZeLUzYyTkcN8RNT7eBBc4A5dvPz/GUA6gJkRg8ADuMljM+eEwYUKT6LS
            XAE/t3q8+o0KfqBZ+eb/3SSiWO0CT5driSnVPSvS3rw6PNn7QGWUxBuHEMgtPNne
            M7uhnEICx6e/odzMHvE4UmIgG5fWs0XTZcSN4M3VUHJRK/AYx34aH746ubLJ
            =l13/
            -----END PGP MESSAGE-----
          fp: 3F21093C93ADBA2108D2BA16787A6911AAEF4539
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
