apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    finalizers:
      - finalizers.fluxcd.io
    name: flux-system
    namespace: flux-system
spec:
  force: false
  interval: 10m0s
  path: ./kustomize/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
