apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base
  - ../../api
  - ./docker-registry-creds.yaml
  - ./ingress.yaml
patches:
  # add the SOPS-encrypted GHCR credentials to the deployment workload
  - target:
      kind: Deployment
      name: github-csat-api
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value: [{ name: ghcr-creds }]
