apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-csat-api
  labels:
    app: github-csat-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: github-csat-api
  template:
    metadata:
      labels:
        app: github-csat-api
    spec:
      containers:
        - name: api
          image: ghcr.io/github-csat/github-csat-api:main
          ports:
            - containerPort: 8080