name: Static Checks

on: pull_request

jobs:
  static:
    name: static Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm --prefix frontend install
      - run: make ci
